### ISSUE TITLE
Lumme: printti-ilmoitukset jumahtaneet 13.2.23

### ISSUE THREAD

**Issue by Katja-Lumme** [KohaSuomi/koha-suomi-messaging#1]
### Mikä vikana?

Asiakkaille ei ole lähtenyt printti-ilmoituksia 13.2. lähtien (pending-tilassa).

**Comment by janPasi** [comment]
Suljetko @Katja-Lumme tiketin.

**Comment by Katja-Lumme** [comment]
Jesh, suljettu:)
