### ISSUE TITLE
Suomi.fi-viestien lähetys asiakkaille joilla ei ole henkilötunnusta.

### ISSUE THREAD

**Issue by johannaraisa** [KohaSuomi/koha-suomi-messaging#2]
Lisätään mahdollisuus lähettää Suomi.fi-viestejä henkilöille joilla ei ole henkilötunnusta.

**Comment by AnneliO** [comment]
Testataan elokuussa Lastussa.

**Comment by johannaraisa** [comment]
Tämä on testattu Lastun kanssa ja toimii.
